/**
 * 五个阶段 + 28 章骨架。
 *
 * 章节顺序与 K.N.King《C 语言程序设计：现代方法》一致（这也是本项目的教学路线），
 * 但**说明文字、目标、讲义、示例与习题全部是原创**，不抄录原书任何内容。
 *
 * `pdfFrom/pdfTo` 是实测出的原书 PDF 页码区间（用于课时页的"延伸阅读"指引，
 * 只给页码不给原文）。PDF 页码 = 书内页码 + 21。
 */
import { chapterSchema, partSchema, type Chapter, type Part } from "@/lib/content/schema";

export const PARTS: Part[] = [
  {
    id: "FOUNDATION",
    name: "C 入门",
    chapterRange: "第 1~3 章",
    detail: "先让程序跑起来：看懂一个最简单的程序、把数据存进变量、把结果打印出来。",
  },
  {
    id: "BUILDING_BLOCKS",
    name: "基本构件",
    chapterRange: "第 4~7 章",
    detail: "程序的四块积木：怎么算（表达式）、怎么选（分支）、怎么重复（循环）、用什么类型存数据。",
  },
  {
    id: "ORGANIZING",
    name: "组织数据与逻辑",
    chapterRange: "第 8~10 章",
    detail: "程序变长以后：一批数据用数组装、重复逻辑用函数封、代码用作用域规则组织起来。",
  },
  {
    id: "POINTERS",
    name: "指针与抽象",
    chapterRange: "第 11~17 章",
    detail: "C 的分水岭：内存地址、字符串的本质、预处理宏、结构体与自定义数据类型。",
  },
  {
    id: "ENGINEERING",
    name: "工程与标准库",
    chapterRange: "第 18~28 章",
    detail: "从会写代码到会做东西：声明与链接、程序设计、底层编程、标准库与错误处理。",
  },
];

const rawChapters: Chapter[] = [
  {
    order: 1,
    slug: "ch01-introducing-c",
    title: "C 语言概述",
    subtitle: "为什么要学 C，以及它今天还在被用在哪",
    part: "FOUNDATION",
    pdfFrom: 22,
    pdfTo: 27,
    summary: "搞清楚 C 是什么、能干什么、为什么值得学，以及一个 C 程序从源代码到运行要经过哪几步。",
    goals: ["说清 C 的定位与适用场景", "讲明白编译、链接大致在做什么", "看懂并运行第一个程序"],
    available: true,
  },
  {
    order: 2,
    slug: "ch02-fundamentals",
    title: "C 语言基本概念",
    subtitle: "变量、赋值、输入输出与程序的形状",
    part: "FOUNDATION",
    pdfFrom: 28,
    pdfTo: 47,
    summary: "把「变量」这件事讲透：怎么声明、怎么赋值、怎么从键盘读进来，以及代码该怎么排版。",
    goals: ["写得出声明与赋值的语句", "用 scanf 读入用户输入", "读懂编译错误在说什么"],
    available: true,
  },
  {
    order: 3,
    slug: "ch03-formatted-io",
    title: "格式化输入/输出",
    subtitle: "printf 与 scanf 的转换说明",
    part: "FOUNDATION",
    pdfFrom: 48,
    pdfTo: 60,
    summary: "printf/scanf 是初学者最常打交道的两个函数，也是最早踩坑的地方：宽度、精度、类型不匹配、忘记取地址符。",
    goals: ["控制输出的宽度、精度与对齐", "用 scanf 正确读入多种类型", "定位并修好常见输入输出错误"],
    available: true,
  },
  {
    order: 4,
    slug: "ch04-expressions",
    title: "表达式",
    subtitle: "算术运算、优先级与类型转换",
    part: "BUILDING_BLOCKS",
    pdfFrom: 61,
    pdfTo: 75,
    summary: "表达式是 C 的骨架。这一章重点讲清整数除法、取余、优先级与结合性这些「一错就全错」的细节。",
    goals: ["正确使用算术与赋值运算符", "用优先级与括号表达意图", "预判表达式的类型与结果"],
    available: true,
  },
  {
    order: 5,
    slug: "ch05-selection",
    title: "选择语句",
    subtitle: "关系运算、if 与 switch",
    part: "BUILDING_BLOCKS",
    pdfFrom: 77,
    pdfTo: 97,
    summary: "让程序会判断：比较、逻辑组合、多路分支，以及 else 悬挂与相等比较这两类经典错误。",
    goals: ["写清 if/else if/else 的分支逻辑", "用逻辑运算符组合条件", "在 if 与 switch 之间做选择"],
    available: true,
  },
  {
    order: 6,
    slug: "ch06-loops",
    title: "循环",
    subtitle: "while、do-while 与 for",
    part: "BUILDING_BLOCKS",
    pdfFrom: 99,
    pdfTo: 117,
    summary: "让程序会重复：三种循环的选择、break/continue 的边界、嵌套循环，以及死循环怎么排查。",
    goals: ["按场景选对循环写法", "用 break/continue 控制流程", "排查死循环与差一错误"],
    available: true,
  },
  {
    order: 7,
    slug: "ch07-basic-types",
    title: "基本类型",
    subtitle: "整数、浮点、字符与它们的取值范围",
    part: "BUILDING_BLOCKS",
    pdfFrom: 119,
    pdfTo: 143,
    summary: "类型决定能存什么、能存多大。这一章把整数溢出、浮点精度、字符与整数互转这些坑一次讲清。",
    goals: ["按取值范围选对类型", "解释整数溢出与浮点误差", "安全地在类型之间转换"],
    available: true,
  },
  {
    order: 8,
    slug: "ch08-arrays",
    title: "数组",
    subtitle: "一批同类型数据的容器",
    part: "ORGANIZING",
    pdfFrom: 145,
    pdfTo: 161,
    summary: "数组让「100 个成绩」不用写 100 个变量。重点是与下标、边界和初始化有关的错误。",
    goals: ["定义并遍历一维/二维数组", "正确处理下标边界", "用数组解决统计类问题"],
    available: true,
  },
  {
    order: 9,
    slug: "ch09-functions",
    title: "函数",
    subtitle: "把重复逻辑封装起来",
    part: "ORGANIZING",
    pdfFrom: 163,
    pdfTo: 191,
    summary: "函数是程序从「能跑」到「能维护」的第一步。核心是理解值传递：函数拿到的是副本，不是原件。",
    goals: ["定义并调用带参数、带返回值的函数", "解释值传递与形参实参", "把重复逻辑抽成函数"],
    available: true,
  },
  {
    order: 10,
    slug: "ch10-program-organization",
    title: "程序结构",
    subtitle: "作用域、全局变量与代码的组织顺序",
    part: "ORGANIZING",
    pdfFrom: 193,
    pdfTo: 207,
    summary: "同样能跑的代码，为什么有的好改有的不敢动？这一章讲清作用域规则与变量的生命周期。",
    goals: ["说清局部/全局变量的作用域与寿命", "避免滥用全局变量", "按合理顺序组织单文件程序"],
    available: true,
  },
  {
    order: 11,
    slug: "ch11-pointers",
    title: "指针",
    subtitle: "内存地址与解引用",
    part: "POINTERS",
    pdfFrom: 209,
    pdfTo: 221,
    summary: "指针不是魔法，它就是一个存地址的变量。把它当普通变量看待，后面的一切都顺了。",
    goals: ["解释地址、指针与解引用的关系", "用指针间接修改数据", "识别未初始化与悬空指针"],
    available: false,
  },
  {
    order: 12,
    slug: "ch12-pointers-arrays",
    title: "指针和数组",
    subtitle: "为什么 a[i] 等价于 *(a+i)",
    part: "POINTERS",
    pdfFrom: 223,
    pdfTo: 237,
    summary: "数组名在大多数场合会退化成指向首元素的指针——理解这一点，函数传数组的写法就自然了。",
    goals: ["解释数组与指针的等价关系", "用指针遍历数组", "正确书写数组形参"],
    available: false,
  },
  {
    order: 13,
    slug: "ch13-strings",
    title: "字符串",
    subtitle: "以空字符结尾的字符数组",
    part: "POINTERS",
    pdfFrom: 239,
    pdfTo: 265,
    summary: "C 没有字符串类型，只有以 \\0 结尾的字符数组。这决定了 strlen 为什么这样写、为什么字符串不能直接赋值比较。",
    goals: ["用字符串字面量与字符数组", "使用 string.h 常用函数", "避开缓冲区溢出"],
    available: false,
  },
  {
    order: 14,
    slug: "ch14-preprocessor",
    title: "预处理器",
    subtitle: "宏、条件编译与头文件",
    part: "POINTERS",
    pdfFrom: 267,
    pdfTo: 291,
    summary: "预处理器在编译之前动你的代码。理解它，才知道 #define 和 const 的区别、头文件为什么要有包含卫士。",
    goals: ["正确使用宏与宏参数", "用条件编译处理平台差异", "写出可重复包含的头文件"],
    available: false,
  },
  {
    order: 15,
    slug: "ch15-large-programs",
    title: "编写大型程序",
    subtitle: "多文件编译、链接与头文件设计",
    part: "POINTERS",
    pdfFrom: 293,
    pdfTo: 313,
    summary: "程序超过几百行就要分文件。这一章讲清声明与定义的分工，以及链接错误的读法。",
    goals: ["把程序拆成多个源文件", "设计对外接口（头文件）", "排查重复定义与未定义符号"],
    available: false,
  },
  {
    order: 16,
    slug: "ch16-structures",
    title: "结构、联合和枚举",
    subtitle: "自定义数据类型",
    part: "POINTERS",
    pdfFrom: 317,
    pdfTo: 343,
    summary: "把相关数据打包成一个类型：结构体描述实体、联合共享内存、枚举给常量起名字。",
    goals: ["定义并使用结构体", "理解结构体的传参与返回", "按场景选用 union 与 enum"],
    available: false,
  },
  {
    order: 17,
    slug: "ch17-advanced-pointers",
    title: "指针的高级应用",
    subtitle: "动态内存、函数指针与链表",
    part: "POINTERS",
    pdfFrom: 345,
    pdfTo: 379,
    summary: "运行期才知道要多少内存时，就得用 malloc。加上函数指针与链表，C 的表达力才算完整。",
    goals: ["用 malloc/free 管理动态内存", "用函数指针做回调", "实现并遍历链表"],
    available: false,
  },
  {
    order: 18,
    slug: "ch18-declarations",
    title: "声明",
    subtitle: "复杂声明的读法与作用域细节",
    part: "ENGINEERING",
    pdfFrom: 381,
    pdfTo: 399,
    summary: "读懂 `int *(*x[10])(void);` 这类声明，靠的不是背规则，而是掌握「从标识符往外读」的方法。",
    goals: ["读得懂复杂指针声明", "写得出数组指针与函数指针", "区分存储类说明符的语义"],
    available: false,
  },
  {
    order: 19,
    slug: "ch19-program-design",
    title: "程序设计",
    subtitle: "从需求到结构",
    part: "ENGINEERING",
    pdfFrom: 401,
    pdfTo: 417,
    summary: "写代码之前的功夫：拆解问题、设计数据结构、给模块划边界。这一章决定你的程序能不能长大。",
    goals: ["把需求拆成可实现的模块", "为问题选择合适的数据结构", "写清模块的职责边界"],
    available: false,
  },
  {
    order: 20,
    slug: "ch20-low-level",
    title: "底层程序设计",
    subtitle: "位运算与内存视角",
    part: "ENGINEERING",
    pdfFrom: 419,
    pdfTo: 433,
    summary: "把数据当比特看：位运算、位域、volatile 与内存对齐。写驱动、协议、嵌入式时绕不开。",
    goals: ["用位运算处理标志与掩码", "解释位域与内存布局", "知道何时需要 volatile"],
    available: false,
  },
  {
    order: 21,
    slug: "ch21-standard-library",
    title: "标准库",
    subtitle: "标准库的整体地图",
    part: "ENGINEERING",
    pdfFrom: 435,
    pdfTo: 443,
    summary: "先建立地图：标准库有哪些头文件、各自负责什么，避免重复造轮子或误用工具。",
    goals: ["说出常用头文件的职责", "知道去哪查标准库函数", "按需引入而不是全量包含"],
    available: false,
  },
  {
    order: 22,
    slug: "ch22-io",
    title: "输入/输出",
    subtitle: "流、文件与缓冲",
    part: "ENGINEERING",
    pdfFrom: 445,
    pdfTo: 481,
    summary: "把「流」这个概念搞清楚，就能举一反三：键盘、文件、字符串都能用同一套接口读写。",
    goals: ["打开/读写/关闭文件", "用重定向与管道", "解释缓冲带来的现象"],
    available: false,
  },
  {
    order: 23,
    slug: "ch23-numbers-chars",
    title: "库对数值和字符数据的支持",
    subtitle: "math、ctype 与数值转换",
    part: "ENGINEERING",
    pdfFrom: 483,
    pdfTo: 511,
    summary: "数学函数、字符分类与字符串转数字——做数据处理时天天要用，也是错误处理的源头。",
    goals: ["使用 math.h 与 ctype.h 常用函数", "安全地做字符串与数值互转", "处理转换失败的返回值"],
    available: false,
  },
  {
    order: 24,
    slug: "ch24-error-handling",
    title: "错误处理",
    subtitle: "断言、errno 与退出码",
    part: "ENGINEERING",
    pdfFrom: 513,
    pdfTo: 521,
    summary: "程序总会出错。这一章讲清「该崩溃时崩溃、该降级时降级」的判断，以及怎么把错误信息传出去。",
    goals: ["用 assert 与 errno 定位问题", "设计合理的错误返回约定", "用退出码与日志表达失败原因"],
    available: false,
  },
  {
    order: 25,
    slug: "ch25-internationalization",
    title: "国际化特性",
    subtitle: "字符集、locale 与宽字符",
    part: "ENGINEERING",
    pdfFrom: 523,
    pdfTo: 551,
    summary: "中文为什么会在某些场合显示成乱码？这一章从字符集与 locale 讲起，给出可操作的判断方法。",
    goals: ["解释字符集与编码的关系", "知道 locale 影响哪些行为", "在需要时使用宽字符"],
    available: false,
  },
  {
    order: 26,
    slug: "ch26-misc-library",
    title: "其他库函数",
    subtitle: "随机数、时间与跳转",
    part: "ENGINEERING",
    pdfFrom: 553,
    pdfTo: 573,
    summary: "补上剩余常用工具：随机数怎么用才真随机、时间怎么取与格式化、setjmp 该在什么场合出现。",
    goals: ["正确播种并使用随机数", "获取与格式化时间", "知道 setjmp/longjmp 的适用边界"],
    available: false,
  },
  {
    order: 27,
    slug: "ch27-additional-language",
    title: "附加语言特性",
    subtitle: "C99 引入的实用特性",
    part: "ENGINEERING",
    pdfFrom: 575,
    pdfTo: 599,
    summary: "复合字面量、指定初始化器、变长数组、inline、restrict——让代码更简洁也更安全的现代写法。",
    goals: ["用指定初始化器写清晰的初始化", "按场景使用变长数组", "理解 restrict 的优化含义"],
    available: false,
  },
  {
    order: 28,
    slug: "ch28-c1x",
    title: "C1X 语言特性",
    subtitle: "标准演进中的新东西",
    part: "ENGINEERING",
    pdfFrom: 601,
    pdfTo: 640,
    summary: "了解标准演进方向：泛型选择、线程与原子操作、静态断言等。知道有这些工具，将来查得着。",
    goals: ["知道 _Generic 的用法", "了解 C 的线程与原子接口", "判断新特性是否值得引入项目"],
    available: false,
  },
];

/** 校验一遍（启动时就会暴露手写错误，而不是等页面渲染炸掉） */
export const CHAPTERS: Chapter[] = rawChapters.map((c) => chapterSchema.parse(c));

export const PARTS_VALIDATED: Part[] = PARTS.map((p) => partSchema.parse(p));

export const CHAPTER_BY_ORDER = new Map(CHAPTERS.map((c) => [c.order, c]));
export const CHAPTER_BY_SLUG = new Map(CHAPTERS.map((c) => [c.slug, c]));

export function getPart(id: Part["id"]): Part {
  const p = PARTS_VALIDATED.find((x) => x.id === id);
  if (!p) throw new Error(`未知阶段：${id}`);
  return p;
}

export function chaptersOfPart(id: Part["id"]): Chapter[] {
  return CHAPTERS.filter((c) => c.part === id).sort((a, b) => a.order - b.order);
}
