/**
 * 第 1~10 章（MVP 范围）的课时列表。
 *
 * 每章 4~6 节，统一节奏：概念节（READING，15~25 分钟）+ 每章一节动手课（LAB，25~30 分钟）。
 * 一节只讲一件事——小白放弃的高峰通常出现在"一节课里塞了三个新概念"的时候。
 *
 * `takeaway` 是这一节的一句话结论，会显示在课程地图和课时页顶部。
 */
import { lessonSchema, type Lesson } from "@/lib/content/schema";

const raw: Lesson[] = [
  // ── 第 1 章 C 语言概述 ─────────────────────────────────────────────
  {
    chapterOrder: 1,
    slug: "why-c",
    order: 1,
    title: "C 到底是一门什么样的语言",
    kind: "READING",
    minutes: 15,
    xp: 10,
    takeaway: "C 是「贴近机器的高级语言」：它不替你管理内存，换来的是对性能与硬件的掌控力。",
  },
  {
    chapterOrder: 1,
    slug: "from-source-to-program",
    order: 2,
    title: "从源代码到能运行的程序",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "预处理 → 编译 → 链接三步走：报错出现在哪一步，决定了你该去查什么。",
  },
  {
    chapterOrder: 1,
    slug: "first-program",
    order: 3,
    title: "拆开第一个程序",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "一个 C 程序的最小骨架就是 main 函数 + 一对花括号；printf 只是它调用的一个函数。",
  },
  {
    chapterOrder: 1,
    slug: "lab-read-the-error",
    order: 4,
    title: "动手：故意把程序改坏",
    kind: "LAB",
    minutes: 25,
    xp: 20,
    takeaway: "编译错误是你的免费老师：先看第一行，再看行号，它通常一次只报一个真问题。",
  },

  // ── 第 2 章 C 语言基本概念 ─────────────────────────────────────────
  {
    chapterOrder: 2,
    slug: "variables-and-assignment",
    order: 1,
    title: "变量：给数据起个名字",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "声明 = 告诉编译器「我要一个存这种数据的盒子」；赋值 = 往盒子里放东西。",
  },
  {
    chapterOrder: 2,
    slug: "printf-basics",
    order: 2,
    title: "把结果打印出来",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "printf 的格式串是模板，%d 这类转换说明会被后面的参数依次填进去。",
  },
  {
    chapterOrder: 2,
    slug: "scanf-basics",
    order: 3,
    title: "让用户输入数据",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "scanf 需要的是「数据放在哪」，所以变量前面要加 &——这一点和 printf 完全不同。",
  },
  {
    chapterOrder: 2,
    slug: "identifiers-and-comments",
    order: 4,
    title: "标识符、关键字与注释",
    kind: "READING",
    minutes: 15,
    xp: 10,
    takeaway: "好的名字比注释有用；注释解释「为什么」，而不是复述「做了什么」。",
  },
  {
    chapterOrder: 2,
    slug: "layout-and-style",
    order: 5,
    title: "代码的排版与风格",
    kind: "READING",
    minutes: 15,
    xp: 10,
    takeaway: "排版不是审美问题：一致的缩进和空行能让 bug 自己浮出来。",
  },
  {
    chapterOrder: 2,
    slug: "lab-first-calculator",
    order: 6,
    title: "动手：把公式写成程序",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "把数学公式翻译成 C 的表达式时，先确定单位与类型，再写运算。",
  },

  // ── 第 3 章 格式化输入/输出 ────────────────────────────────────────
  {
    chapterOrder: 3,
    slug: "printf-conversions",
    order: 1,
    title: "printf 的转换说明",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "%d/%f/%c/%s 各管一种类型，用错不会报错，只会打印出莫名其妙的值。",
  },
  {
    chapterOrder: 3,
    slug: "width-precision-align",
    order: 2,
    title: "宽度、精度与对齐",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "%8.2f = 总宽 8、小数 2 位；加上负号就是左对齐。表格对齐全靠它。",
  },
  {
    chapterOrder: 3,
    slug: "scanf-deep",
    order: 3,
    title: "scanf 到底怎么读输入",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "scanf 按格式串「跳过空白 → 匹配 → 转换」；读不进去时它会停在原地，后面的输入就全乱了。",
  },
  {
    chapterOrder: 3,
    slug: "io-pitfalls",
    order: 4,
    title: "输入输出的五个经典坑",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "忘记 &、类型不匹配、%c 读到换行、缓冲区没刷、格式串里乱加字符——这五个坑占了新手报错的大半。",
  },
  {
    chapterOrder: 3,
    slug: "lab-report-card",
    order: 5,
    title: "动手：做一张对齐的成绩单",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "读入多个数据、算出平均分、按固定宽度排版输出——这就是一个完整的迷你程序。",
  },

  // ── 第 4 章 表达式 ────────────────────────────────────────────────
  {
    chapterOrder: 4,
    slug: "arithmetic",
    order: 1,
    title: "算术运算符与整数除法",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "两个 int 相除只保留整数部分：1/2 是 0，不是 0.5。这是新手第一个「见鬼了」的时刻。",
  },
  {
    chapterOrder: 4,
    slug: "precedence",
    order: 2,
    title: "优先级与结合性",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "不确定优先级时加括号——括号不花钱，猜错的代价是调试半小时。",
  },
  {
    chapterOrder: 4,
    slug: "assignment-operators",
    order: 3,
    title: "赋值运算符与自增自减",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "i++ 与 ++i 在单独成句时没区别；一旦嵌进表达式，就是可读性灾难的起点。",
  },
  {
    chapterOrder: 4,
    slug: "type-conversion",
    order: 4,
    title: "表达式里的类型转换",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "不同类型混算时会发生隐式转换，方向是「往精度高的那边走」；想改结果就用强制转换。",
  },
  {
    chapterOrder: 4,
    slug: "lab-check-digit",
    order: 5,
    title: "动手：算校验位",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "用取余与整除拆开一个整数的每一位，是很多算法题的基本功。",
  },

  // ── 第 5 章 选择语句 ──────────────────────────────────────────────
  {
    chapterOrder: 5,
    slug: "booleans-and-relations",
    order: 1,
    title: "关系运算与真假",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "C 里没有真正的布尔类型（传统写法）：0 是假，非 0 都是真——包括 -1。",
  },
  {
    chapterOrder: 5,
    slug: "if-else",
    order: 2,
    title: "if、else if 与 else",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "多路分支的顺序很重要：条件要从最特殊写到最一般，否则后面的分支永远进不去。",
  },
  {
    chapterOrder: 5,
    slug: "logical-operators",
    order: 3,
    title: "逻辑运算符与短路求值",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "&& 和 || 会短路：左边一旦能定结果，右边根本不执行——这既能省事也能埋雷。",
  },
  {
    chapterOrder: 5,
    slug: "switch-and-conditional",
    order: 4,
    title: "switch 与条件表达式",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "switch 适合「一个值对应多个固定分支」；忘了 break 会一路穿下去，这是它最大的坑。",
  },
  {
    chapterOrder: 5,
    slug: "lab-grade-and-leap-year",
    order: 5,
    title: "动手：成绩等级与闰年判断",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "把一串 if 写对的关键是：先写出所有边界，再决定谁先判断。",
  },

  // ── 第 6 章 循环 ──────────────────────────────────────────────────
  {
    chapterOrder: 6,
    slug: "while",
    order: 1,
    title: "while：先判断再执行",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "while 循环要能结束，必须满足：循环体里有东西在改变循环条件。",
  },
  {
    chapterOrder: 6,
    slug: "do-while-and-for",
    order: 2,
    title: "do-while 与 for",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "次数已知用 for，至少执行一次用 do-while，其余用 while——按场景选，别硬套一种。",
  },
  {
    chapterOrder: 6,
    slug: "break-continue",
    order: 3,
    title: "break 与 continue",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "break 跳出整个循环，continue 只跳过本轮——嵌套循环里它们只影响最内层。",
  },
  {
    chapterOrder: 6,
    slug: "nested-loops",
    order: 4,
    title: "嵌套循环与死循环排查",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "外层管「第几轮」，内层管「这一轮做什么」；死循环先查循环变量有没有真的在变。",
  },
  {
    chapterOrder: 6,
    slug: "lab-prime-and-guess",
    order: 5,
    title: "动手：素数判断与猜数字",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "能用「提前结束」的循环不要硬跑到底——这既是最基本的效率意识，也是逻辑清晰的表现。",
  },

  // ── 第 7 章 基本类型 ──────────────────────────────────────────────
  {
    chapterOrder: 7,
    slug: "integer-types",
    order: 1,
    title: "整数类型与取值范围",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "short/int/long 能存多大是平台相关的；要精确控制宽度就用 stdint.h 里的定长类型。",
  },
  {
    chapterOrder: 7,
    slug: "floating-types",
    order: 2,
    title: "浮点类型与精度陷阱",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "0.1 + 0.2 != 0.3 不是 C 的 bug，是二进制浮点的本质；比较浮点数要用误差范围。",
  },
  {
    chapterOrder: 7,
    slug: "char-type",
    order: 3,
    title: "字符类型与字符运算",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "char 本质是小整数：'A' 就是 65，所以 'a' - 'A' = 32 这种换算才成立。",
  },
  {
    chapterOrder: 7,
    slug: "sizeof-and-casts",
    order: 4,
    title: "sizeof、强制转换与 typedef",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "sizeof 是编译期算出的字节数；强制转换只改变「怎么解释这串比特」，不改变比特本身。",
  },
  {
    chapterOrder: 7,
    slug: "lab-overflow",
    order: 5,
    title: "动手：亲眼看到整数溢出",
    kind: "LAB",
    minutes: 25,
    xp: 20,
    takeaway: "溢出不会报错，只会悄悄变成另一个数——所以选类型前要先估算最大可能值。",
  },

  // ── 第 8 章 数组 ──────────────────────────────────────────────────
  {
    chapterOrder: 8,
    slug: "one-dimensional",
    order: 1,
    title: "一维数组的定义与遍历",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "数组让「一批同类型数据」共用一个名字，用下标区分——循环和数组是天生一对。",
  },
  {
    chapterOrder: 8,
    slug: "initialization-bounds",
    order: 2,
    title: "初始化与越界",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "C 不检查下标越界：a[10] 在长度为 10 的数组上是越界访问，可能什么也不发生，也可能崩。",
  },
  {
    chapterOrder: 8,
    slug: "two-dimensional",
    order: 3,
    title: "二维数组",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "二维数组就是「数组的数组」：a[i] 是一整行，a[i][j] 才是那一行里的某个元素。",
  },
  {
    chapterOrder: 8,
    slug: "lab-stats-and-matrix",
    order: 4,
    title: "动手：统计与矩阵转置",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "求最值/平均这类问题的通用套路：先假设第一个是答案，再逐个比较更新。",
  },

  // ── 第 9 章 函数 ──────────────────────────────────────────────────
  {
    chapterOrder: 9,
    slug: "define-and-call",
    order: 1,
    title: "为什么需要函数",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "函数把「做什么」和「怎么做的细节」分开，是控制复杂度的第一件工具。",
  },
  {
    chapterOrder: 9,
    slug: "pass-by-value",
    order: 2,
    title: "参数传递：值传递的真相",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "C 永远传副本：函数里改形参不会影响调用方的变量——想改原件只能传地址。",
  },
  {
    chapterOrder: 9,
    slug: "return-and-void",
    order: 3,
    title: "返回值与 return",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "return 一执行，函数立刻结束；忘了写返回值的函数会返回垃圾数据。",
  },
  {
    chapterOrder: 9,
    slug: "arrays-as-arguments",
    order: 4,
    title: "数组作为参数",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "数组传参实际传的是首元素地址，所以函数里改数组会改到原件——长度必须另外传。",
  },
  {
    chapterOrder: 9,
    slug: "scope-and-recursion",
    order: 5,
    title: "作用域与递归入门",
    kind: "READING",
    minutes: 25,
    xp: 10,
    takeaway: "递归 = 函数调用自己 + 一个能停下来的条件；没有终止条件就是栈溢出。",
  },
  {
    chapterOrder: 9,
    slug: "lab-toolbox",
    order: 6,
    title: "动手：写一个自己的小工具库",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "把重复出现的代码抽成函数后，主程序应该短到一眼能读完。",
  },

  // ── 第 10 章 程序结构 ─────────────────────────────────────────────
  {
    chapterOrder: 10,
    slug: "local-and-global",
    order: 1,
    title: "局部变量与全局变量",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "局部变量用完就没了，全局变量整个程序活着——能用局部就别用全局。",
  },
  {
    chapterOrder: 10,
    slug: "blocks-and-scope",
    order: 2,
    title: "块与作用域规则",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "花括号划出作用域；内层可以遮蔽外层同名变量，这正是 bug 的高发区。",
  },
  {
    chapterOrder: 10,
    slug: "organizing-one-file",
    order: 3,
    title: "把单文件程序排好序",
    kind: "READING",
    minutes: 20,
    xp: 10,
    takeaway: "惯例顺序：包含 → 宏 → 类型 → 函数原型 → main → 各函数实现。这样读代码的人不用来回跳。",
  },
  {
    chapterOrder: 10,
    slug: "lab-split-program",
    order: 4,
    title: "动手：把一个大程序整理干净",
    kind: "LAB",
    minutes: 30,
    xp: 20,
    takeaway: "重构的第一步不是改逻辑，而是给已有逻辑起好名字、排好位置。",
  },
];

export const LESSONS: Lesson[] = raw.map((l) => lessonSchema.parse(l));

/** 某章的课时（按 order 排序） */
export function lessonsOfChapter(chapterOrder: number): Lesson[] {
  return LESSONS.filter((l) => l.chapterOrder === chapterOrder).sort(
    (a, b) => a.order - b.order,
  );
}

export const TOTAL_MINUTES = LESSONS.reduce((s, l) => s + l.minutes, 0);
export const TOTAL_XP = LESSONS.reduce((s, l) => s + l.xp, 0);
